//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzApp.API.Infrastructure.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzApp.API.Infrastructure.Localizations.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქალაქის სახელი უნდა იყოს 15 სიმბოლომდე.
        /// </summary>
        public static string CityError {
            get {
                return ResourceManager.GetString("CityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩანაწერი უკვე არსებობს.
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ქვეყნის სახელი უნდა იყოს 15 სიმბოლომდე.
        /// </summary>
        public static string CountryError {
            get {
                return ResourceManager.GetString("CountryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ელექტრონული ფოსტა შეყვანილი იქნა არასწორ ფორმატში.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ველი არ შეიძლება იყოს ცარიელი.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to მოხდა შეცდომა.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ჩანაწერი ვერ მოიძებნა.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to შეყვანილი ნომერი არასწორ ფორმატშია.
        /// </summary>
        public static string PhoneNumberFormat {
            get {
                return ResourceManager.GetString("PhoneNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 პიცაზე მეტიის დამატება ჯერ ვერ ხერხდება.
        /// </summary>
        public static string Pizza {
            get {
                return ResourceManager.GetString("Pizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიცის კალორიები უნდა იყოს მეტი 0-ზე.
        /// </summary>
        public static string PizzaCalory {
            get {
                return ResourceManager.GetString("PizzaCalory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიცის აღწერა უნდა იყო 100 სიმბოლოზე ნაკლები.
        /// </summary>
        public static string PizzaDescription {
            get {
                return ResourceManager.GetString("PizzaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიცის სახელი უნდა იყოს 2-ან 20 სიმბოლომდე.
        /// </summary>
        public static string PizzaError {
            get {
                return ResourceManager.GetString("PizzaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ორდერში არ არის პიცები.
        /// </summary>
        public static string PizzaExist {
            get {
                return ResourceManager.GetString("PizzaExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to პიცის ფასი უნდა აღემატებოდეს 0-ს.
        /// </summary>
        public static string PizzaPrice {
            get {
                return ResourceManager.GetString("PizzaPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რანკები უნდა იყოს 1 დან 10მდე.
        /// </summary>
        public static string RankAmount {
            get {
                return ResourceManager.GetString("RankAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to რეგიონის სახელი უნდა იყოს 15 სიმბოლომდე .
        /// </summary>
        public static string RegionError {
            get {
                return ResourceManager.GetString("RegionError", resourceCulture);
            }
        }
    }
}
